### ISSUE TITLE
Italian version.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#36]
I think I have most of the pieces I need for an Italian version of Citation Hunt. Hopefully going from 2 to 3 languages will be easier than going from 1 to 2 :)

**Roadmap**

- [ ] Figure out whether the Italian Wikipedia has a special policy for citations in the lead section (like [WP:CITELEAD](https://en.wikipedia.org/wiki/WP:CITELEAD) in English) and get a link to that if it does.
- [x] Find a good introductory page about referencing (like [Aide:Source](https://fr.wikipedia.org/wiki/Aide:Pr%C3%A9sentez_vos_sources) in French).
- [x] Add basic configuration for Italian to the [configuration](https://github.com/eggpi/citationhunt/blob/master/config.py) and try [parsing the dumps](https://github.com/eggpi/citationhunt/tree/master/scripts).
- [x] Implement a few of the most important Italian-specific templates in the [snippet_parser](https://github.com/eggpi/citationhunt/tree/master/snippet_parser) package.
- [x] Link to it from the other languages.

/cc @Aubreymcfato @pepato

**Comment by ricordisamoa** [comment]
> Figure out whether the Italian Wikipedia has a special policy for citations in the lead section (like [WP:CITELEAD](//en.wikipedia.org/wiki/WP:CITELEAD) in English) and get a link to that if it does.

[WP:CITIN](//it.wikipedia.org/wiki/WP:CITIN)

**Comment by eggpi** [comment]
Thanks! 4bb73b9 will link to WP:CITIN.

**Comment by nemobis** [comment]
ricordisamoa, 20/02/2016 16:21:
> WP:CITIN <//it.wikipedia.org/wiki/WP:CITIN>

That's about quotations, not citations.

**Comment by ricordisamoa** [comment]
> That's about quotations, not citations.

:open_mouth: :fearful: :cold_sweat: :sob:

**Comment by eggpi** [comment]
> Figure out whether the Italian Wikipedia has a special policy for citations in the lead section (like WP:CITELEAD in English) and get a link to that if it does.

OK, I couldn't find one, but this is optional anyway. Let's merge this to master.
