### ISSUE TITLE
Investigate enabling html_snippet for more languages.

### ISSUE THREAD

**Issue by eggpi** [eggpi/citationhunt#81]
In `html_snippet` mode, we convert the snippet to HTML, then remove stuff like images and tables, before storing it in the database.

The advantage here is that we handle all templates, so this may or not yield better results than trying to clean up the wikicode ourselves. I wouldn't be surprised if different languages had different results using this, though, and maybe there are trade-offs I'm not aware of yet.

`html_snippet` is currently enabled for dewiki and lvwiki, and in the [fr branch](https://github.com/eggpi/citationhunt/tree/fr), I'm trying it out for frwiki.

**Comment by eggpi** [comment]
Issues that block (or, at least, are very closely related to) this:

- [ ] Move away from wikitools. (#80)
- [ ] Snippet overflows when resizing the window on Chrome, Safari (#73)
- [ ] Add a simple stylesheet for snippets. (#68)

**Comment by eggpi** [comment]
I think we're pretty close to this in French, and the next will likely be Chinese. #91 and #88 have some interesting information about parsing zhwiki, since that seems to require some undocumented API parameters.
